# Generated by Django 3.2.9 on 2021-11-20 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 11, 14, 13, 136705), null=True),
        ),
    ]
